Repository gogatekeeper/gatekeeper, pull requests merged in 2022-09, with the labels that each got.

#207 Add docu related to auth flows
  docs/user-guide.md
Labels: documentation

#208 No proxy headers match
  config.go
  config_test.go
  doc.go
  docs/user-guide.md
  middleware.go
  middleware_test.go
  pkg/authorization/resource.go
  pkg/authorization/resource_test.go
  server.go
  server_test.go
Labels: enhancement

#210 log client_ip field with real ip value (#209)
  forwarding.go
  handlers.go
  middleware.go
  middleware_test.go
Labels: enhancement

#211 Update docs for 1.7.0
  README.md
  doc.go
  docs/settings.md
  docs/user-guide.md
  kube/reverse.yml
Labels: documentation

#213 Add OPA External Authorization
  .github/workflows/build.yml
  config.go
  config_test.go
  doc.go
  go.mod
  go.sum
  middleware.go
  middleware_test.go
  pkg/apperrors/apperrors.go
  pkg/authorization/external.go
  pkg/authorization/external_keycloak.go
  pkg/authorization/external_opa.go
  pkg/authorization/external_opa_test.go
  server.go
Labels: enhancement

#215 Remove non-transparent behaviour when default-deny and /* defined in …
  config.go
  config_test.go
  pkg/apperrors/apperrors.go
  server.go
  server_test.go
Labels: bug, enhancement

#216 Default Deny strict was returning 401 in auth_code flow instead of re…
  middleware.go
  server_test.go
Labels: bug, easy
