Repository gogatekeeper/gatekeeper, pull requests merged in 2024-07, with the labels that each got.

#477 Gdpr logs
  pkg/keycloak/proxy/handlers.go
  pkg/proxy/middleware/base.go
  pkg/proxy/middleware/oauth.go
  pkg/proxy/middleware/security.go
  pkg/testsuite/middleware_test.go
  pkg/utils/token.go
Labels: enhancement

#483 Update docu for 2.13.0
  README.md
  docs/content/userguide/_index.md
  e2e/k8s/manifest_test_forwardauth.yml
  kube/reverse.yml
Labels: documentation

#484 Workaround golang cgroup issue
  go.mod
  go.sum
  pkg/keycloak/proxy/server.go
Labels: bug

#487 Fix documentation link
  README.md
Labels: documentation

#488 Enable to forward-auth to work with static authz
  pkg/keycloak/proxy/server.go
  pkg/proxy/middleware/base.go
  pkg/testsuite/server_test.go
Labels: bug

#490 Remove deprecated WithOauth method
  pkg/google/config/config.go
  pkg/keycloak/proxy/oauth_proxy.go
  pkg/keycloak/proxy/server.go
Labels: refactor

#491 Small lint improvements
  pkg/constant/constant.go
  pkg/keycloak/proxy/forwarding.go
  pkg/keycloak/proxy/handlers.go
  pkg/keycloak/proxy/middleware.go
  pkg/keycloak/proxy/misc.go
  pkg/keycloak/proxy/server.go
Labels: refactor

#492 Test lint improvements
  pkg/testsuite/constant.go
  pkg/testsuite/cookies_test.go
  pkg/testsuite/fake_authserver.go
  pkg/testsuite/fake_proxy.go
  pkg/testsuite/handlers_test.go
  pkg/testsuite/middleware_test.go
  pkg/testsuite/server_test.go
  pkg/testsuite/session_test.go
Labels: refactor

#494 Fix remaining lint warnings
  .github/workflows/build.yml
  e2e/e2e_init_test.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  e2e/e2e_uma_test.go
  pkg/apperrors/apperrors.go
  pkg/authorization/external_opa.go
  pkg/authorization/external_opa_test.go
  pkg/authorization/resource.go
  pkg/config/core/core.go
  pkg/constant/constant.go
  pkg/encryption/self_signed.go
  pkg/google/config/config.go
  pkg/keycloak/config/config.go
  pkg/keycloak/config/config_test.go
  pkg/keycloak/proxy/handlers.go
  pkg/proxy/cli.go
  pkg/proxy/cookie/cookies.go
  pkg/proxy/core/helpers.go
  pkg/proxy/middleware/base.go
  pkg/proxy/session/token.go
  pkg/storage/storage.go
  pkg/testsuite/constant.go
  pkg/testsuite/fake_authserver.go
  pkg/testsuite/fake_proxy.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: refactor

#496 Update docu 2.14.0
  README.md
  docs/content/userguide/_index.md
  e2e/k8s/manifest_test_forwardauth.yml
  kube/reverse.yml
Labels: documentation
